### ISSUE TITLE
Superseded?

### ISSUE THREAD

**Issue by lishaduck** [smores56/weaver#1]
Given roc-lang/basic-cli#204, is this library supplanted and superseded by the new Args module? i.e., is this deprecated, or is it still meant to stick around as an agnostic framework not tied to any specific platform?

This was probably clarified on the Zulip somewhere, but I don't use Zulip.
Thanks for your time!

**Comment by smores56** [comment]
That's a good question! We did indeed have some discussion about it [here](https://roc.zulipchat.com/#narrow/stream/383402-API-Design/topic/Removing.20.60Arg.60.20module.20from.20basic-cli/near/437381896) in the Zulip chat.

The idea is that while the old `Arg` interface was not as good as Weaver's is, and people should prefer using Weaver, the core team doesn't want Roc and its platforms to be dependent on external packages while the language itself is so unstable. If they need to update Weaver to make a syntax change, the release process would be hampered significantly, especially if they start doing this with other packages, like Url's, HTTP, etc. So in recognizing the value of having something like Weaver when writing any CLI app, for now we just embedded in into the `basic-cli` platform to subvert the issue.

In the future, once `Task` is added as a built-in and module params are implemented, then packages like Weaver are easier to drop in to user packages without needing to be built in to the language. I expect we'll remove the copy of Weaver from `basic-cli` once this is possible.

In the meantime, what's should you use this package?
- If you use the `basic-cli` platform, you may as well use its version of Weaver, they're basically the same right now
- If you use a different platform, you'll still need to use Weaver to parse arguments
- If you want to avoid switching back to Weaver when new features are added or it is potentially removed from the `basic-cli` platform, you can still always use it directly

**Comment by lishaduck** [comment]
Ah, ok! I was just wondering if it was still ok to be used. I'm glad to hear it'll remain—I like the name 😄[^1]

[^1]: Why are these emojis so creepy? I was going to go with a laugh, but... no...
